---
title: "A Turn Toward Urban Attacks? Descriptive Evidence from the GTD"
author: "Cameron Reed, Sascha Schuster, Lukas Bretzinger"
date: "November 14, 2014"
output: html_document
---


```{r, echo=FALSE}
#Start up PreGTD

ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg))
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

# usage
packages <- c("foreign", "car", "RCurl", "ggplot2", "WDI", "httr", "iterators", "dplyr", "plyr",
              "XML", "maps", "ggmap", "Imap", "geosphere", "maptools", "rgeos", "foreach")
ipak(packages)
rm(packages)
rm(ipak)

#download a limited GTD we created for this assignment
PreGTD_in_Memory <- getURL("https://rawgit.com/LBRETZIN/UrbanTerror/master/PreAnalysis/pregtd.csv", ssl.verifypeer=0L, followlocation=1L)
writeLines(PreGTD_in_Memory,'Pre.GTD.csv')
rm(PreGTD_in_Memory)

#Load the Pre-Analysis Global Terrorism Database
PreGTD <- read.csv("Pre.GTD.csv", header=TRUE)
PreGTD <-PreGTD[order(-PreGTD$eventid, na.last=TRUE) , ]
PreGTD$X <- NULL

# make numeric what we need
PreGTD$EN.URB.LCTY.UR.ZS <- as.numeric(PreGTD$EN.URB.LCTY.UR.ZS)
PreGTD$SP.URB.TOTL <- as.numeric(PreGTD$SP.URB.TOTL)
PreGTD$SP.RUR.TOTL <- as.numeric(PreGTD$SP.RUR.TOTL)
PreGTD$MAX.URB.TOTL <- as.numeric(PreGTD$MAX.URB.TOTL)
PreGTD$pop <- as.numeric(PreGTD$pop)

# some simple new variables, most interesting the relative.city.population_to.largest.city in country!
RegGTD <- data.frame(PreGTD$eventid, PreGTD$iyear)
RegGTD["year"] <- as.numeric(PreGTD$iyear-1970)
RegGTD["city.population_2013"] <- PreGTD$pop
RegGTD["city.population_at.attack.time_liniear.grown"] <- ((PreGTD$pop)*(PreGTD$SP.URB.TOTL)/(PreGTD$MAX.URB.TOTL))
RegGTD["relative.city.population_to.largest.city" ] <- (PreGTD$pop*PreGTD$SP.URB.TOTL/PreGTD$MAX.URB.TOTL/
                                                          ((PreGTD$SP.URB.TOTL+PreGTD$SP.RUR.TOTL)*(100/PreGTD$EN.URB.LCTY.UR.ZS)))

RegGTD$relative.city.population_to.largest.city[is.na(RegGTD$relative.city.population_to.largest.city)] <- 0

# test für eine lineare regression
Linear1 <- lm((relative.city.population_to.largest.city*100) ~ year, data = RegGTD)
summary(Linear1)
plot(Linear1, which = 2)

# Trying out a scatterplotMatrix (time intensive)
Plot <- RegGTD
Plot$PreGTD.iyear <- NULL
Plot$PreGTD.eventid <- NULL
Plot$city.population_at.attack.time_liniear.grown <- NULL
Plot$city.population_2013 <- NULL

# Change PROPscale and HUMscale to its yearly Summs
PropSUMs <-aggregate(Plot$PROPscale, by=list(Plot$year), FUN=sum)
PropSUMs["year"] <- PropSUMs$Group.1 
PropSUMs["PROPscale.SUM"] <- PropSUMs$x
PropSUMs$Group.1 <- NULL
PropSUMs$x <- NULL
Plot <- merge(Plot, PropSUMs, by="year")
PropSUMs <-aggregate(Plot$PROPscale, by=list(Plot$year), FUN=sum)
HumSUMs <-aggregate(Plot$HUMscale, by=list(Plot$year), FUN=sum)
HumSUMs["year"] <- HumSUMs$Group.1 
HumSUMs["HUMcale.SUM"] <- HumSUMs$x
HumSUMs$Group.1 <- NULL
HumSUMs$x <- NULL
Plot <- merge(Plot, HumSUMs, by="year")
Plot$HUMscale <- NULL
Plot$PROPscale <- NULL


#make a scatterplotMatrix with year, relative population size of attacked city, yearly HUMscale and PPROscale
#######
# TIME INTENSIVE!
#######
scatterplotMatrix(Plot)

# take a look at the structure of our data
str(PreGTD)

# make a table of attacks in capital cities per year
cap.table0<-with(PreGTD, table(iyear, capital))
cap.table <- subset(PreGTD, capital==1, select=1:30)
cap.table<-as.data.frame(cap.table)

#now just year and capital
cap.table<-with(cap.table, table(iyear, capital))
summary(cap.table)

# some quick counts of in urban center, part of urban centers, and in both
count(PreGTD, "in.urban.centers.environment")
count(PreGTD, "part.of.urban.center")
count(PreGTD, c("in.urban.centers.environment", "part.of.urban.center"))


```{r}
library(plyr)
count(PreGTD, c("iyear", "region_txt"))
```
