# put in costal megacities
# extracted from .Rhistory
# to append to main file

###############If not sure, add here#########################
UrbanCenters$costalMC[UrbanCenters$City == "cairo"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "kolkata"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "bankok"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "dhaka"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "london"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "hangzhou"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "houston"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "porto alegre"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "melbourne"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "sapporo"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "guayaquil"] <- "1"
##############################################################
##############################################################


#####Main Set######
UrbanCenters$costalMC=0
UrbanCenters$costalMC[UrbanCenters$City == "tokyo"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "jakarta"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "seoul"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "shanghai"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "manila"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "karachi"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "new york city"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "sao paolo"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "mumbai"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "osaka"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "los angeles"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "buenos aires"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "istanbul"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "shenzen"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "lagos"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "rio de janeiro"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "nagoya"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "lima"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "chennai"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "chicago"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "hong kong"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "toronto"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "san francisco"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "miami"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "quanzhou"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "luanda"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "singapore"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "saint petersburg"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "surat"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "surabaya"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "abidjan"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "alexandria"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "barcelona"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "qingdao"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "suzhou"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "salvador"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "sydney"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "accra"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "recife"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "kuwait city"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "dalian"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "naples"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "dar es salaam"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "fuzhou"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "fortaleza"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "cape town"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "athens"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "durban"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "wuxi"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "tel aviv"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "jeddah"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "xiamen"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "busan"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "dubai"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "ningbo"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "dakar"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "seattle"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "chittagong"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "san diego"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "casablanca"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "algiers"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "taichung"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "izmir"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "wenzhou"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "kaohsiung"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "lisbon"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "maputo"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "douala"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "fukoka"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "tampa"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "tunis"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "cebu city"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "shantou"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "port-au-prince"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "zhongshan"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "santo domingo"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "medan"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "baltimore"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "kochi"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "panama city"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "colombo"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "vancouver"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "san juan"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "kozhikode"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "belem"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "baku"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "havana"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "tangshan"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "kitakyushu"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "beirut"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "port harcourt"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "barranquilla"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "brisbane"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "portland"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "valencia"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "rabat"] <- "1"
UrbanCenters$costalMC[UrbanCenters$City == "lome"] <- "1"
