

WC.UC.dist <- read.csv("WC.UC.dist.csv", header=TRUE)

PreGTD <- read.csv('TerrorData/Pregtd.csv')

X <- subset(PreGTD, !is.na(GTD.city) & is.na(WCUC.city) & TUPscale!=(0|1|2|3))

X$GTD.city <- sub("district", NA, X$GTD.city)
X$GTD.city <- sub("^$", NA, X$GTD.city)
X$GTD.city <- sub("^ $", NA, X$GTD.city)
X$GTD.city <- sub(".community$", NA, X$GTD.city)
X$GTD.city <- sub(".commune$", NA, X$GTD.city)
X$GTD.city <- sub(".dist$", NA, X$GTD.city)
X$GTD.city <- sub(".prov$", NA, X$GTD.city)
X$GTD.city <- sub(".island$", NA, X$GTD.city)
X$GTD.city <- sub(".area$", NA, X$GTD.city)
X$GTD.city <- sub(".border$", NA, X$GTD.city)
X$GTD.city <- sub(".hwy$", NA, X$GTD.city)
X$GTD.city <- sub(".dept$", NA, X$GTD.city)
X$GTD.city <- sub("nationwide", NA, X$GTD.city)
X$GTD.city <- sub(".valley$", NA, X$GTD.city)
X$GTD.city <- sub(".department$", NA, X$GTD.city)
X$GTD.city <- sub(".state$", NA, X$GTD.city)
X$GTD.city <- sub(".beach$", NA, X$GTD.city)
X$GTD.city <- sub("^westbank$", NA, X$GTD.city)
X$GTD.city <- sub("^negev$", NA, X$GTD.city)
X$GTD.city <- sub(".desert$", NA, X$GTD.city)
X$GTD.city <- sub(".forest$", NA, X$GTD.city)
X$GTD.city <- sub("^sansalvador$", NA, X$GTD.city)
X$GTD.city <- sub("^northcacharhills", NA, X$GTD.city)
X$GTD.city <- sub("corsica$", NA, X$GTD.city)
X$GTD.city <- sub("between.", NA, X$GTD.city)
X$GTD.city <- sub("road.", NA, X$GTD.city)
X$GTD.city <- sub("highway.", NA, X$GTD.city)
X$GTD.city <- sub("province", NA, X$GTD.city)
X$GTD.city <- sub("municipality", NA, X$GTD.city)
X$GTD.city <- sub("station", NA, X$GTD.city)
X$GTD.city <- sub("forwardoperatingbase", NA, X$GTD.city)
X$GTD.city <- sub("rwanda", NA, X$GTD.city)
X$GTD.city <- sub("russianfederation", NA, X$GTD.city)
X$GTD.city <- sub("iraq", NA, X$GTD.city)
X$GTD.city <- sub("unitedstates", NA, X$GTD.city)
X$GTD.city <- sub("nepal", NA, X$GTD.city)
X$GTD.city <- sub("mozambique", NA, X$GTD.city)
X$GTD.city <- sub("algeria", NA, X$GTD.city)
X$GTD.city <- sub("burundi", NA, X$GTD.city)
X$GTD.city <- sub("angola", NA, X$GTD.city)
X$GTD.city <- sub("bangladesh", NA, X$GTD.city)
X$GTD.city <- sub("sudan", NA, X$GTD.city)
X$GTD.city <- sub("nicaragua", NA, X$GTD.city)
X$GTD.city <- sub("lebanon", NA, X$GTD.city)
X$GTD.city <- sub("india", NA, X$GTD.city)
X$GTD.city <- sub("indonesia", NA, X$GTD.city)
X$GTD.city <- sub("srilanka", NA, X$GTD.city)
X$GTD.city <- sub("pakistan", NA, X$GTD.city)
X$GTD.city <- sub("punjab", NA, X$GTD.city)
X$GTD.city <- sub("westbankandgaza", NA, X$GTD.city)
X$GTD.city <- sub("yemenrep", NA, X$GTD.city)
X$GTD.city <- sub("afghanistan", NA, X$GTD.city)
X$GTD.city <- sub("egyptarabrep", NA, X$GTD.city)
X$GTD.city <- sub("elsalvador", NA, X$GTD.city)
X$GTD.city <- sub("nigeria", NA, X$GTD.city)
X$GTD.city <- sub("syrianarabrepublic", NA, X$GTD.city)
X$GTD.city <- sub("cambodia", NA, X$GTD.city)
X$GTD.city <- sub("chad", NA, X$GTD.city)
X$GTD.city <- sub("china", NA, X$GTD.city)
X$GTD.city <- sub("colombia", NA, X$GTD.city)
X$GTD.city <- sub("tunisia", NA, X$GTD.city)
X$GTD.city <- sub("ethiopia", NA, X$GTD.city)
X$GTD.city <- sub("norway", NA, X$GTD.city)
X$GTD.city <- sub("israel", NA, X$GTD.city)
X$GTD.city <- sub("southafrica", NA, X$GTD.city)
X$GTD.city <- sub("southsudan", NA, X$GTD.city)
X$GTD.city <- sub("djibouti", NA, X$GTD.city)
X$GTD.city <- sub("uganda", NA, X$GTD.city)
X$GTD.city <- sub("unitedarabemirates", NA, X$GTD.city)
X$GTD.city <- sub("congorep", NA, X$GTD.city)
X$GTD.city <- sub("saudiarabia", NA, X$GTD.city)
X$GTD.city <- sub("sierraleone", NA, X$GTD.city)
X$GTD.city <- sub("guatemala", NA, X$GTD.city)
X$GTD.city <- sub("malaysia", NA, X$GTD.city)
X$GTD.city <- sub("spain", NA, X$GTD.city)
X$GTD.city <- sub("philippines", NA, X$GTD.city)
X$GTD.city <- sub("myanmar", NA, X$GTD.city)
X$GTD.city <- sub("greece", NA, X$GTD.city)
X$GTD.city <- sub("kenya", NA, X$GTD.city)
X$GTD.city <- sub("peru", NA, X$GTD.city)
X$GTD.city <- sub("unitedkingdom", NA, X$GTD.city)
X$GTD.city <- sub("vietnam", NA, X$GTD.city)
X$GTD.city <- sub("turkey", NA, X$GTD.city)
X$GTD.city <- sub("guinea", NA, X$GTD.city)
X$GTD.city <- sub("barbados", NA, X$GTD.city)
X$GTD.city <- sub("iranislamicrep", NA, X$GTD.city)
X$GTD.city <- sub("azerbaijan", NA, X$GTD.city)
X$GTD.city <- sub("somalia", NA, X$GTD.city)
X$GTD.city <- sub("congodemrep", NA, X$GTD.city)
X$GTD.city <- sub("mali", NA, X$GTD.city)
X$GTD.city <- sub("korearep", NA, X$GTD.city)
X$GTD.city <- sub("armenia", NA, X$GTD.city)
X$GTD.city <- sub("kosovo", NA, X$GTD.city)
X$GTD.city <- sub("senegal", NA, X$GTD.city)
X$GTD.city <- sub("morocco", NA, X$GTD.city)
X$GTD.city <- sub("namibia", NA, X$GTD.city)
X$GTD.city <- sub("thailand", NA, X$GTD.city)
X$GTD.city <- sub("germany", NA, X$GTD.city)
X$GTD.city <- sub("hongkongsarchina", NA, X$GTD.city)
X$GTD.city <- sub("mexico", NA, X$GTD.city)
X$GTD.city <- sub("mauritania", NA, X$GTD.city)
X$GTD.city <- sub("honduras", NA, X$GTD.city)
X$GTD.city <- sub("niger", NA, X$GTD.city)
X$GTD.city <- sub("moldova", NA, X$GTD.city)
X$GTD.city <- sub("bolivia", NA, X$GTD.city)
X$GTD.city <- sub("zambia", NA, X$GTD.city)
X$GTD.city <- sub("centralafricanrepublic", NA, X$GTD.city)
X$GTD.city <- sub("georgia", NA, X$GTD.city)
X$GTD.city <- sub("cameroon", NA, X$GTD.city)
X$GTD.city <- sub("uzbekistan", NA, X$GTD.city)
X$GTD.city <- sub("zimbabwe", NA, X$GTD.city)
X$GTD.city <- sub("grenada", NA, X$GTD.city)
X$GTD.city <- sub("guineabissau", NA, X$GTD.city)
X$GTD.city <- sub("venezuelarb", NA, X$GTD.city)
X$GTD.city <- sub("eritrea", NA, X$GTD.city)
X$GTD.city <- sub("tajikistan", NA, X$GTD.city)
X$GTD.city <- sub("jamaica", NA, X$GTD.city)
X$GTD.city <- sub("france", NA, X$GTD.city)
X$GTD.city <- sub("kuwait", NA, X$GTD.city)
X$GTD.city <- sub("cotedivoire", NA, X$GTD.city)
X$GTD.city <- sub("newcaledonia", NA, X$GTD.city)
X$GTD.city <- sub("libya", NA, X$GTD.city)
X$GTD.city <- sub("macaosarchina", NA, X$GTD.city)
X$GTD.city <- sub("paraguay", NA, X$GTD.city)
X$GTD.city <- sub("guyana", NA, X$GTD.city)
X$GTD.city <- sub("macedoniafyr", NA, X$GTD.city)
X$GTD.city <- sub("brazil", NA, X$GTD.city)
X$GTD.city <- sub("chile", NA, X$GTD.city)
X$GTD.city <- sub("haiti", NA, X$GTD.city)
X$GTD.city <- sub("laopdr", NA, X$GTD.city)
X$GTD.city <- sub("lesotho", NA, X$GTD.city)
X$GTD.city <- sub("suriname", NA, X$GTD.city)
X$GTD.city <- sub("albania", NA, X$GTD.city)
X$GTD.city <- sub("ecuador", NA, X$GTD.city)
X$GTD.city <- sub("liberia", NA, X$GTD.city)
X$GTD.city <- sub("ukraine", NA, X$GTD.city)
X$GTD.city <- sub("bosniaandherzegovina", NA, X$GTD.city)
X$GTD.city <- sub("papuanewguinea", NA, X$GTD.city)
X$GTD.city <- sub("bahrain", NA, X$GTD.city)
X$GTD.city <- sub("ireland", NA, X$GTD.city)
X$GTD.city <- sub("switzerland", NA, X$GTD.city)
X$GTD.city <- sub("bhutan", NA, X$GTD.city)
X$GTD.city <- sub("botswana", NA, X$GTD.city)
X$GTD.city <- sub("italy", NA, X$GTD.city)
X$GTD.city <- sub("lithuania", NA, X$GTD.city)
X$GTD.city <- sub("timorleste", NA, X$GTD.city)
X$GTD.city <- sub("cyprus", NA, X$GTD.city)
X$GTD.city <- sub("jordan", NA, X$GTD.city)
X$GTD.city <- sub("kyrgyzrepublic", NA, X$GTD.city)
X$GTD.city <- sub("poland", NA, X$GTD.city)
X$GTD.city <- sub("serbia", NA, X$GTD.city)
X$GTD.city <- sub("sovietunion", NA, X$GTD.city)
X$GTD.city <- sub("cuba", NA, X$GTD.city)
X$GTD.city <- sub("dominicanrepublic", NA, X$GTD.city)
X$GTD.city <- sub("gabon", NA, X$GTD.city)
X$GTD.city <- sub("madagascar", NA, X$GTD.city)
X$GTD.city <- sub("panama", NA, X$GTD.city)
X$GTD.city <- sub("austria", NA, X$GTD.city)
X$GTD.city <- sub("costarica", NA, X$GTD.city)
X$GTD.city <- sub("ghana", NA, X$GTD.city)
X$GTD.city <- sub("kazakhstan", NA, X$GTD.city)
X$GTD.city <- sub("netherlands", NA, X$GTD.city)
X$GTD.city <- sub("qatar", NA, X$GTD.city)
X$GTD.city <- sub("togo", NA, X$GTD.city)
X$GTD.city <- sub("yugoslavia", NA, X$GTD.city)
X$GTD.city <- sub("argentina", NA, X$GTD.city)
X$GTD.city <- sub("hungary", NA, X$GTD.city)
X$GTD.city <- sub("malawi", NA, X$GTD.city)
X$GTD.city <- sub("portugal", NA, X$GTD.city)
X$GTD.city <- sub("puertorico", NA, X$GTD.city)
X$GTD.city <- sub("slovakrepublic", NA, X$GTD.city)
X$GTD.city <- sub("solomonislands", NA, X$GTD.city)
X$GTD.city <- sub("sweden", NA, X$GTD.city)
X$GTD.city <- sub("tanzania", NA, X$GTD.city)
X$GTD.city <- sub("trinidadandtobago", NA, X$GTD.city)
X$GTD.city <- sub("bulgaria", NA, X$GTD.city)
X$GTD.city <- sub("canada", NA, X$GTD.city)
X$GTD.city <- sub("comoros", NA, X$GTD.city)
X$GTD.city <- sub("croatia", NA, X$GTD.city)
X$GTD.city <- sub("czechrepublic", NA, X$GTD.city)
X$GTD.city <- sub("equatorialguinea", NA, X$GTD.city)
X$GTD.city <- sub("estonia", NA, X$GTD.city)
X$GTD.city <- sub("japan", NA, X$GTD.city)
X$GTD.city <- sub("latvia", NA, X$GTD.city)
X$GTD.city <- sub("luxembourg", NA, X$GTD.city)
X$GTD.city <- sub("montenegro", NA, X$GTD.city)
X$GTD.city <- sub("antiguaandbarbuda", NA, X$GTD.city)
X$GTD.city <- sub("australia", NA, X$GTD.city)
X$GTD.city <- sub("bahamasthe", NA, X$GTD.city)
X$GTD.city <- sub("belarus", NA, X$GTD.city)
X$GTD.city <- sub("belgium", NA, X$GTD.city)
X$GTD.city <- sub("belize", NA, X$GTD.city)
X$GTD.city <- sub("benin", NA, X$GTD.city)
X$GTD.city <- sub("denmark", NA, X$GTD.city)
X$GTD.city <- sub("fiji", NA, X$GTD.city)
X$GTD.city <- sub("iceland", NA, X$GTD.city)
X$GTD.city <- sub("slovenia", NA, X$GTD.city)
X$GTD.city <- sub("swaziland", NA, X$GTD.city)
X$GTD.city <- sub("vanuatu", NA, X$GTD.city)

X$GTD.city <- sub("kilometer", NA, X$GTD.city)
X$GTD.city <- sub("mountains", NA, X$GTD.city)
X$GTD.city <- sub("airbase", NA, X$GTD.city)
X$GTD.city <- sub("distcrict", NA, X$GTD.city)
X$GTD.city <- sub("highlands", NA, X$GTD.city)
X$GTD.city <- sub("hills", NA, X$GTD.city)
X$GTD.city <- sub("regimiento", NA, X$GTD.city)
X$GTD.city <- sub("junction", NA, X$GTD.city)
X$GTD.city <- sub("north", NA, X$GTD.city)
X$GTD.city <- sub("south", NA, X$GTD.city)
X$GTD.city <- sub("west", NA, X$GTD.city)
X$GTD.city <- sub("east", NA, X$GTD.city)

X <- subset(X, !is.na(GTD.city))

X$X <- 1
List <- aggregate(X$X, by=list(X$GTD.city), FUN=sum)
List <- List[order(-List$x), ]
rm(X)
List <- merge(List, PreGTD, by.x=c("Group.1"), by.y=c("GTD.city"), all.x=TRUE)
List <- subset(List, is.na(List$old.pop))
List <- List[!duplicated(List$merge),]
Missing <- subset(List, select=c("country_txt", "Group.1", "x", "original.city"))
Missing["attacks"] <- Missing$x
Missing$x <- NULL
Missing <- Missing[order(-Missing$attacks), ]
rm(List)


X <- subset(Missing, attacks>=3 & attacks<=150)
X["lookup"] <- paste(X$Group.1, X$country_txt, sep=", ")





missingLOC <- geocode(X$lookup, output = c("latlon", "latlona", "more", "all"), messaging = FALSE, sensor = FALSE, override_limit = TRUE)
missingLOC["CityGTD"] <- X$GTD.city
missingLOC <- subset(missingLOC, !is.na(lon))
ZZZ <- subset(WC.UC.dist, select = c("long", "lat", "name")) 
ZZZ$fake=1
missingLOC$fake=1


save <- read.csv('missing.8ormore.csv')
l<- split(save, sample(rep(1:6, 220)))
ll<-l[[2]]
lll<-l[[3]]
llll <-l[[4]]
lllll <-l[[5]]
llllll <-l[[6]]
l<-l[[1]]

missingLOC <- l
Zil <-merge(ZZZ, missingLOC, by=c("fake"))
Zil$lon <- as.numeric(Zil$lon)
Zil$lat.y <- as.numeric(Zil$lat.y)
Zil$long <- as.numeric(Zil$long)
Zil$lat.x <- as.numeric(Zil$lat.x)
Zil["DistKM"] <- gdist(lon.1=Zil$lon, lat.1=Zil$lat.y, lon.2=Zil$long, lat.2=Zil$lat.x, units = "km", a = 6378137, b = 6356752, verbose = FALSE)
Zil.min <- aggregate(DistKM ~ CityGTD, Zil, function(x) min(x))
missing.distances <- merge(Zil.min, Zil, by=c("CityGTD", "DistKM"))
missing.distances <- missing.distances[order(missing.distances$DistKM),]
write.csv(missing.distances, file="missing.l8ormore.csv")

missingLOC <- ll
Zil <-merge(ZZZ, missingLOC, by=c("fake"))
Zil$lon <- as.numeric(Zil$lon)
Zil$lat.y <- as.numeric(Zil$lat.y)
Zil$long <- as.numeric(Zil$long)
Zil$lat.x <- as.numeric(Zil$lat.x)
Zil["DistKM"] <- gdist(lon.1=Zil$lon, lat.1=Zil$lat.y, lon.2=Zil$long, lat.2=Zil$lat.x, units = "km", a = 6378137, b = 6356752, verbose = FALSE)
Zil.min <- aggregate(DistKM ~ CityGTD, Zil, function(x) min(x))
missing.distances <- merge(Zil.min, Zil, by=c("CityGTD", "DistKM"))
missing.distances <- missing.distances[order(missing.distances$DistKM),]
write.csv(missing.distances, file="missing.ll8ormore.csv")

missingLOC <- lll
Zil <-merge(ZZZ, missingLOC, by=c("fake"))
Zil$lon <- as.numeric(Zil$lon)
Zil$lat.y <- as.numeric(Zil$lat.y)
Zil$long <- as.numeric(Zil$long)
Zil$lat.x <- as.numeric(Zil$lat.x)
Zil["DistKM"] <- gdist(lon.1=Zil$lon, lat.1=Zil$lat.y, lon.2=Zil$long, lat.2=Zil$lat.x, units = "km", a = 6378137, b = 6356752, verbose = FALSE)
Zil.min <- aggregate(DistKM ~ CityGTD, Zil, function(x) min(x))
missing.distances <- merge(Zil.min, Zil, by=c("CityGTD", "DistKM"))
missing.distances <- missing.distances[order(missing.distances$DistKM),]
write.csv(missing.distances, file="missing.lll8ormore.csv")

missingLOC <- llll
Zil <-merge(ZZZ, missingLOC, by=c("fake"))
Zil$lon <- as.numeric(Zil$lon)
Zil$lat.y <- as.numeric(Zil$lat.y)
Zil$long <- as.numeric(Zil$long)
Zil$lat.x <- as.numeric(Zil$lat.x)
Zil["DistKM"] <- gdist(lon.1=Zil$lon, lat.1=Zil$lat.y, lon.2=Zil$long, lat.2=Zil$lat.x, units = "km", a = 6378137, b = 6356752, verbose = FALSE)
Zil.min <- aggregate(DistKM ~ CityGTD, Zil, function(x) min(x))
missing.distances <- merge(Zil.min, Zil, by=c("CityGTD", "DistKM"))
missing.distances <- missing.distances[order(missing.distances$DistKM),]
write.csv(missing.distances, file="missing.llll8ormore.csv")

missingLOC <- lllll
Zil <-merge(ZZZ, missingLOC, by=c("fake"))
Zil$lon <- as.numeric(Zil$lon)
Zil$lat.y <- as.numeric(Zil$lat.y)
Zil$long <- as.numeric(Zil$long)
Zil$lat.x <- as.numeric(Zil$lat.x)
Zil["DistKM"] <- gdist(lon.1=Zil$lon, lat.1=Zil$lat.y, lon.2=Zil$long, lat.2=Zil$lat.x, units = "km", a = 6378137, b = 6356752, verbose = FALSE)
Zil.min <- aggregate(DistKM ~ CityGTD, Zil, function(x) min(x))
missing.distances <- merge(Zil.min, Zil, by=c("CityGTD", "DistKM"))
missing.distances <- missing.distances[order(missing.distances$DistKM),]
write.csv(missing.distances, file="missing.lllll8ormore.csv")

missingLOC <- llllll
Zil <-merge(ZZZ, missingLOC, by=c("fake"))
Zil$lon <- as.numeric(Zil$lon)
Zil$lat.y <- as.numeric(Zil$lat.y)
Zil$long <- as.numeric(Zil$long)
Zil$lat.x <- as.numeric(Zil$lat.x)
Zil["DistKM"] <- gdist(lon.1=Zil$lon, lat.1=Zil$lat.y, lon.2=Zil$long, lat.2=Zil$lat.x, units = "km", a = 6378137, b = 6356752, verbose = FALSE)
Zil.min <- aggregate(DistKM ~ CityGTD, Zil, function(x) min(x))
missing.distances <- merge(Zil.min, Zil, by=c("CityGTD", "DistKM"))
missing.distances <- missing.distances[order(missing.distances$DistKM),]
write.csv(missing.distances, file="missing.llllll8ormore.csv")


#Missing["CityID"] <- rownames(Missing)
#missing.distances["CityID"] <- rownames(missing.distances)
#XX <- merge(missing.distances, Missing, by=c("CityID"), all.x=TRUE)



rm(missingLOC, ZZ, ZZZ, Zil, Zil.min)
