UrbanCenters$coastalMC=0

#Including dummy variables for coastal megacities

###############If not sure, add here#########################
#UrbanCenters$coastalMC[UrbanCenters$City == "cairo"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "kolkata"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "bankok"] <- "1" # bangkok?
#UrbanCenters$coastalMC[UrbanCenters$City == "dhaka"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "london"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "hangzhou"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "houston"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "porto alegre"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "melbourne"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "sapporo"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "guayaquil"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "johor bahru"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "stockholm"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "changshu"] <- "1"
#UrbanCenters$coastalMC[UrbanCenters$City == "merida"] <- "1"
##############################################################


#####Main Set######

UrbanCenters$coastalMC[UrbanCenters$City == "tokyo"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "jakarta"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "seoul"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "shanghai"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "manila"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "karachi"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "new york city"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "sao paolo"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "mumbai"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "osaka"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "los angeles"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "buenos aires"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "istanbul"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "shenzen"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "lagos"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "rio de janeiro"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "nagoya"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "lima"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "chennai"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "chicago"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "hong kong"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "toronto"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "san francisco"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "miami"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "quanzhou"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "luanda"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "singapore"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "saint petersburg"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "surat"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "surabaya"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "abidjan"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "alexandria"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "barcelona"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "qingdao"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "suzhou"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "salvador"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "sydney"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "accra"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "recife"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "kuwait city"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "dalian"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "naples"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "dar es salaam"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "fuzhou"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "fortaleza"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "cape town"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "athens"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "durban"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "wuxi"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "tel aviv"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "jeddah"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "xiamen"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "busan"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "dubai"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "ningbo"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "dakar"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "seattle"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "chittagong"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "san diego"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "casablanca"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "algiers"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "taichung"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "izmir"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "wenzhou"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "kaohsiung"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "lisbon"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "maputo"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "douala"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "fukoka"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "tampa"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "tunis"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "cebu city"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "shantou"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "port-au-prince"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "zhongshan"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "santo domingo"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "medan"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "baltimore"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "kochi"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "panama city"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "colombo"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "vancouver"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "san juan"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "kozhikode"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "belem"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "baku"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "havana"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "tangshan"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "kitakyushu"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "beirut"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "port harcourt"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "barranquilla"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "brisbane"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "portland"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "rabat"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "lome"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "semarang"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "conakry"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "tijuana"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "visakhapatnam"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "thiruvananthapuram"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "santos"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "vitoria"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "montevideo"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "perth"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "kannur"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "mogadishu"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "haikou"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "makassar"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "marseille"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "davao city"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "virginia beach norfolk"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "porto"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "yantai"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "natal"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "sendai"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "huizhou"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "sao luis"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "hiroshima"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "auckland"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "zhuhai"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "tainan"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "maceio"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "copenhagen"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "cixi city"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "joao pessoa"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "zhangzhou"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "providence"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "tripoli"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "vasai virar"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "helsinki"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "putian"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "dublin"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "kollam"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "jacksonville"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "ulsan"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "haifa"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "florianopolis"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "mombasa"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "dongying"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "amsterdam"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "jiaxing"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "nantong"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "odessa"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "cartagena"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "hamamatsu"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "port elizabeth"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "changwon"] <- "1"
UrbanCenters$coastalMC[UrbanCenters$City == "monrovia"] <- "1"

# There are 2 Valencias. The one in Venezuela is not a CMC, just the one in Spain.
UrbanCenters$coastalMC[UrbanCenters$City == "valencia" & UrbanCenters$Country == "Spain"] <- "1" 