world.cities$country.etc[world.cities$name == "berane"] <- "montenegro"
world.cities$country.etc[world.cities$name == "podgorica"] <- "montenegro"
world.cities$country.etc[world.cities$name == "niksic"] <- "montenegro"
world.cities$country.etc[world.cities$name == "pljevlja"] <- "montenegro"
world.cities$country.etc[world.cities$name == "budva"] <- "montenegro"
world.cities$country.etc[world.cities$name == "cetinje"] <- "montenegro"
world.cities$country.etc[world.cities$country.etc == "serbiaandmontenegro"] <- "serbia"
world.cities$country.etc[world.cities$country.etc == "norfolkisland"] <- "australia"
world.cities$country.etc[world.cities$country.etc == "bahamas"] <- "bahamasthe"
world.cities$country.etc[world.cities$country.etc == "brunei"] <- "bruneidarussalam"
world.cities$country.etc[world.cities$country.etc == "guernseyandalderney"] <- "channelislands"
world.cities$country.etc[world.cities$country.etc == "jersey"] <- "channelislands"
world.cities$country.etc[world.cities$country.etc == "easterisland"] <- "chile"
world.cities$country.etc[world.cities$country.etc == "taiwan"] <- "china"
world.cities$country.etc[world.cities$country.etc == "congodemocraticrepublic"] <- "congodemrep"
world.cities$country.etc[world.cities$country.etc == "congo"] <- "congorep"
world.cities$country.etc[world.cities$country.etc == "ivorycoast"] <- "cotedivoire"
world.cities$country.etc[world.cities$country.etc == "faroeislands"] <- "denmark"
world.cities$country.etc[world.cities$country.etc == "egypt"] <- "egyptarabrep"
world.cities$country.etc[world.cities$country.etc == "frenchguiana"] <- "france"
world.cities$country.etc[world.cities$country.etc == "frenchsouthernterritories"] <- "france"
world.cities$country.etc[world.cities$country.etc == "guadeloupe"] <- "france"
world.cities$country.etc[world.cities$country.etc == "martinique"] <- "france"
world.cities$country.etc[world.cities$country.etc == "mayotte"] <- "france"
world.cities$country.etc[world.cities$country.etc == "reunion"] <- "france"
world.cities$country.etc[world.cities$country.etc == "saint-barthelemy"] <- "france"
world.cities$country.etc[world.cities$country.etc == "saintpierreandmiquelon"] <- "france"
world.cities$country.etc[world.cities$country.etc == "wallisandfutuna"] <- "france"
world.cities$country.etc[world.cities$country.etc == "gambia"] <- "gambiathe"
world.cities$country.etc[world.cities$country.etc == "iran"] <- "iranislamicrep"
world.cities$country.etc[world.cities$country.etc == "koreademocraticpeople'srepublicof"] <- "koreademrep"
world.cities$country.etc[world.cities$country.etc == "korearepublicof"] <- "korearep"
world.cities$country.etc[world.cities$country.etc == "kyrgyzstan"] <- "kyrgyzrepublic"
world.cities$country.etc[world.cities$country.etc == "laos"] <- "laopdr"
world.cities$country.etc[world.cities$country.etc == "macedonia"] <- "macedoniafyr"
world.cities$country.etc[world.cities$country.etc == "micronesia"] <- "micronesiafedsts"
world.cities$country.etc[world.cities$country.etc == "netherlandsantilles"] <- "netherlands"
world.cities$country.etc[world.cities$country.etc == "cookislands"] <- "newzealand"
world.cities$country.etc[world.cities$country.etc == "niue"] <- "newzealand"
world.cities$country.etc[world.cities$country.etc == "tokelau"] <- "newzealand"
world.cities$country.etc[world.cities$country.etc == "svalbardandjanmayen"] <- "norway"
world.cities$country.etc[world.cities$country.etc == "azores"] <- "portugal"
world.cities$country.etc[world.cities$country.etc == "serbiaandmontenegro"] <- "serbia"
world.cities$country.etc[world.cities$country.etc == "slovakia"] <- "slovakrepublic"
world.cities$country.etc[world.cities$country.etc == "canaryislands"] <- "spain"
world.cities$country.etc[world.cities$country.etc == "westernsahara"] <- "spain"
world.cities$country.etc[world.cities$country.etc == "saintkittsandnevis"] <- "stkittsandnevis"
world.cities$country.etc[world.cities$country.etc == "saintlucia"] <- "stlucia"
world.cities$country.etc[world.cities$country.etc == "saint-martin"] <- "stmartinfrenchpart"
world.cities$country.etc[world.cities$country.etc == "saintvincentandthegrenadines"] <- "stvincentandthegrenadines"
world.cities$country.etc[world.cities$country.etc == "syria"] <- "syrianarabrepublic"
world.cities$country.etc[world.cities$country.etc == "turksandcaicos"] <- "turksandcaicosislands"
world.cities$country.etc[world.cities$country.etc == "anguilla"] <- "unitedkingdom"
world.cities$country.etc[world.cities$country.etc == "britishvirginislands"] <- "unitedkingdom"
world.cities$country.etc[world.cities$country.etc == "falklandislands"] <- "unitedkingdom"
world.cities$country.etc[world.cities$country.etc == "gibraltar"] <- "unitedkingdom"
world.cities$country.etc[world.cities$country.etc == "montserrat"] <- "unitedkingdom"
world.cities$country.etc[world.cities$country.etc == "pitcairn"] <- "unitedkingdom"
world.cities$country.etc[world.cities$country.etc == "sainthelena"] <- "unitedkingdom"
world.cities$country.etc[world.cities$country.etc == "northernmarianaislands"] <- "unitedstates"
world.cities$country.etc[world.cities$country.etc == "unitedstatesofamerica"] <- "unitedstates"
world.cities$country.etc[world.cities$country.etc == "venezuela"] <- "venezuelarb"
world.cities$country.etc[world.cities$country.etc == "usvirginislands"] <- "virginislandsus"
world.cities$country.etc[world.cities$country.etc == "palestine"] <- "westbankandgaza"
world.cities$country.etc[world.cities$country.etc == "yemen"] <- "yemenrep"
world.cities$country.etc[world.cities$country.etc == "russia"] <- "russianfederation"

#On another checking process, we found other wrong information that needs correction.
world.cities$capital[world.cities$name == "newdelhi" &  world.cities$country.etc  == "india"] <- 1
world.cities$capital[world.cities$name == "peking" &  world.cities$country.etc  == "china"] <- 1
world.cities$capital[world.cities$name == "beirut" &  world.cities$country.etc  == "lebanon"] <- 1
world.cities$capital[world.cities$name == "guatemalacity" &  world.cities$country.etc  == "guatemala"] <- 1
world.cities$largestC[world.cities$name == "bombay" &  world.cities$country.etc  == "india"] <- 1
world.cities$largestC[world.cities$name == "mexicocity" &  world.cities$country.etc  == "mexico"] <- 1
world.cities$capital[world.cities$name == "mexico" &  world.cities$country.etc  == "mexico"] <- 1

