X <- as.character(X)
X <- gsub("\\,","",X)
X <- gsub("\\-","",X)
X <- gsub("\\-","",X)
X <- gsub("\\-","",X)
X <- gsub("\\'","",X)
X <- gsub("\\'","",X)
X <- gsub("\\.","",X)
X <- gsub("\\\\", "", X)
X <- gsub("\\(","",X)
X <- gsub("\\)","",X)
X<-gsub(" ","",X)
X <- tolower(X)
