
# give a list of missing / unmatched city values in the GTD
X <- subset(PreGTD, is.na(WCUC.city) & !is.na(GTD.city ))
X$GTD.city <- sub("district", NA, X$GTD.city)
X$GTD.city <- sub(".community$", NA, X$GTD.city)
X$GTD.city <- sub(".commune$", NA, X$GTD.city)
X$GTD.city <- sub(".dist$", NA, X$GTD.city)
X$GTD.city <- sub(".area$", NA, X$GTD.city)
X$GTD.city <- sub(".border$", NA, X$GTD.city)
X$GTD.city <- sub(".beach$", NA, X$GTD.city)
X$GTD.city <- sub("between.", NA, X$GTD.city)
X$GTD.city <- sub("road.", NA, X$GTD.city)
X$GTD.city <- sub("highway.", NA, X$GTD.city)
X$GTD.city <- sub("province", NA, X$GTD.city)
X$GTD.city <- sub("municipality", NA, X$GTD.city)
X$GTD.city <- sub("station", NA, XX$GTD.city)
X$GTD.city <- sub("forwardoperatingbase", NA, X$GTD.city)
X$GTD.city <- sub("rwanda", NA, X$GTD.city)
X$GTD.city <- sub("russianfederation", NA, X$GTD.city)
X$GTD.city <- sub("iraq", NA, X$GTD.city)
X$GTD.city <- sub("unitedstates", NA, X$GTD.city)
X$GTD.city <- sub("nepal", NA, X$GTD.city)
X$GTD.city <- sub("mozambique", NA, X$GTD.city)
X$GTD.city <- sub("algeria", NA, X$GTD.city)
X$GTD.city <- sub("burundi", NA, X$GTD.city)
X$GTD.city <- sub("angola", NA, X$GTD.city)
X$GTD.city <- sub("bangladesh", NA, X$GTD.city)
X$GTD.city <- sub("sudan", NA, X$GTD.city)
X$GTD.city <- sub("nicaragua", NA, X$GTD.city)
X$GTD.city <- sub("lebanon", NA, X$GTD.city)
X$GTD.city <- sub("india", NA, X$GTD.city)
X$GTD.city <- sub("indonesia", NA, X$GTD.city)
X$GTD.city <- sub("srilanka", NA, X$GTD.city)
X$GTD.city <- sub("pakistan", NA, X$GTD.city)
X$GTD.city <- sub("westbankandgaza", NA, X$GTD.city)
X$GTD.city <- sub("yemenrep", NA, X$GTD.city)
X$GTD.city <- sub("afghanistan", NA, X$GTD.city)
X$GTD.city <- sub("egyptarabrep", NA, X$GTD.city)
X$GTD.city <- sub("elsalvador", NA, X$GTD.city)
X$GTD.city <- sub("nigeria", NA, X$GTD.city)
X$GTD.city <- sub("syrianarabrepublic", NA, X$GTD.city)
X$GTD.city <- sub("cambodia", NA, X$GTD.city)
X$GTD.city <- sub("chad", NA, X$GTD.city)
X$GTD.city <- sub("china", NA, X$GTD.city)
X$GTD.city <- sub("colombia", NA, X$GTD.city)
X$GTD.city <- sub("tunisia", NA, X$GTD.city)
X$GTD.city <- sub("ethiopia", NA, X$GTD.city)
X$GTD.city <- sub("norway", NA, X$GTD.city)
X$GTD.city <- sub("israel", NA, X$GTD.city)
X$GTD.city <- sub("southafrica", NA, X$GTD.city)
X$GTD.city <- sub("southsudan", NA, X$GTD.city)
X$GTD.city <- sub("djibouti", NA, X$GTD.city)
X$GTD.city <- sub("uganda", NA, X$GTD.city)
X$GTD.city <- sub("unitedarabemirates", NA, X$GTD.city)
X$GTD.city <- sub("congorep", NA, X$GTD.city)
X$GTD.city <- sub("saudiarabia", NA, X$GTD.city)
X$GTD.city <- sub("sierraleone", NA, X$GTD.city)
X$GTD.city <- sub("guatemala", NA, X$GTD.city)
X$GTD.city <- sub("malaysia", NA, X$GTD.city)
X$GTD.city <- sub("spain", NA, X$GTD.city)
X$GTD.city <- sub("philippines", NA, X$GTD.city)
X$GTD.city <- sub("myanmar", NA, X$GTD.city)
X$GTD.city <- sub("greece", NA, X$GTD.city)
X$GTD.city <- sub("kenya", NA, X$GTD.city)
X$GTD.city <- sub("peru", NA, X$GTD.city)
X$GTD.city <- sub("unitedkingdom", NA, X$GTD.city)
X$GTD.city <- sub("vietnam", NA, X$GTD.city)
X$GTD.city <- sub("turkey", NA, X$GTD.city)
X$GTD.city <- sub("guinea", NA, X$GTD.city)
X$GTD.city <- sub("barbados", NA, X$GTD.city)
X$GTD.city <- sub("iranislamicrep", NA, X$GTD.city)
X$GTD.city <- sub("azerbaijan", NA, X$GTD.city)
X$GTD.city <- sub("somalia", NA, X$GTD.city)
X$GTD.city <- sub("congodemrep", NA, X$GTD.city)
X$GTD.city <- sub("mali", NA, X$GTD.city)
X$GTD.city <- sub("korearep", NA, X$GTD.city)
X$GTD.city <- sub("armenia", NA, X$GTD.city)
X$GTD.city <- sub("kosovo", NA, X$GTD.city)
X$GTD.city <- sub("senegal", NA, X$GTD.city)
X$GTD.city <- sub("morocco", NA, X$GTD.city)
X$GTD.city <- sub("namibia", NA, X$GTD.city)
X$GTD.city <- sub("thailand", NA, X$GTD.city)
X$GTD.city <- sub("germany", NA, X$GTD.city)
X$GTD.city <- sub("hongkongsarchina", NA, X$GTD.city)
X$GTD.city <- sub("mexico", NA, X$GTD.city)
X$GTD.city <- sub("mauritania", NA, X$GTD.city)
X$GTD.city <- sub("honduras", NA, X$GTD.city)
X$GTD.city <- sub("niger", NA, X$GTD.city)
X$GTD.city <- sub("moldova", NA, X$GTD.city)
X$GTD.city <- sub("bolivia", NA, X$GTD.city)
X$GTD.city <- sub("zambia", NA, X$GTD.city)
X$GTD.city <- sub("centralafricanrepublic", NA, X$GTD.city)
X$GTD.city <- sub("georgia", NA, X$GTD.city)
X$GTD.city <- sub("cameroon", NA, X$GTD.city)
X$GTD.city <- sub("uzbekistan", NA, X$GTD.city)
X$GTD.city <- sub("zimbabwe", NA, X$GTD.city)
X$GTD.city <- sub("grenada", NA, X$GTD.city)
X$GTD.city <- sub("guineabissau", NA, X$GTD.city)
X$GTD.city <- sub("venezuelarb", NA, X$GTD.city)
X$GTD.city <- sub("eritrea", NA, X$GTD.city)
X$GTD.city <- sub("tajikistan", NA, X$GTD.city)
X$GTD.city <- sub("jamaica", NA, X$GTD.city)
X$GTD.city <- sub("france", NA, X$GTD.city)
X$GTD.city <- sub("kuwait", NA, X$GTD.city)
X$GTD.city <- sub("cotedivoire", NA, X$GTD.city)
X$GTD.city <- sub("newcaledonia", NA, X$GTD.city)
X$GTD.city <- sub("libya", NA, X$GTD.city)
X$GTD.city <- sub("macaosarchina", NA, X$GTD.city)
X$GTD.city <- sub("paraguay", NA, X$GTD.city)
X$GTD.city <- sub("guyana", NA, X$GTD.city)
X$GTD.city <- sub("macedoniafyr", NA, X$GTD.city)
X$GTD.city <- sub("brazil", NA, X$GTD.city)
X$GTD.city <- sub("chile", NA, X$GTD.city)
X$GTD.city <- sub("haiti", NA, X$GTD.city)
X$GTD.city <- sub("laopdr", NA, X$GTD.city)
X$GTD.city <- sub("lesotho", NA, X$GTD.city)
X$GTD.city <- sub("suriname", NA, X$GTD.city)
X$GTD.city <- sub("albania", NA, X$GTD.city)
X$GTD.city <- sub("ecuador", NA, X$GTD.city)
X$GTD.city <- sub("liberia", NA, X$GTD.city)
X$GTD.city <- sub("ukraine", NA, X$GTD.city)
X$GTD.city <- sub("bosniaandherzegovina", NA, X$GTD.city)
X$GTD.city <- sub("papuanewguinea", NA, X$GTD.city)
X$GTD.city <- sub("bahrain", NA, X$GTD.city)
X$GTD.city <- sub("ireland", NA, X$GTD.city)
X$GTD.city <- sub("switzerland", NA, X$GTD.city)
X$GTD.city <- sub("bhutan", NA, X$GTD.city)
X$GTD.city <- sub("botswana", NA, X$GTD.city)
X$GTD.city <- sub("italy", NA, X$GTD.city)
X$GTD.city <- sub("lithuania", NA, X$GTD.city)
X$GTD.city <- sub("timorleste", NA, X$GTD.city)
X$GTD.city <- sub("cyprus", NA, X$GTD.city)
X$GTD.city <- sub("jordan", NA, X$GTD.city)
X$GTD.city <- sub("kyrgyzrepublic", NA, X$GTD.city)
X$GTD.city <- sub("poland", NA, X$GTD.city)
X$GTD.city <- sub("serbia", NA, X$GTD.city)
X$GTD.city <- sub("sovietunion", NA, X$GTD.city)
X$GTD.city <- sub("cuba", NA, X$GTD.city)
X$GTD.city <- sub("dominicanrepublic", NA, X$GTD.city)
X$GTD.city <- sub("gabon", NA, X$GTD.city)
X$GTD.city <- sub("madagascar", NA, X$GTD.city)
X$GTD.city <- sub("panama", NA, X$GTD.city)
X$GTD.city <- sub("austria", NA, X$GTD.city)
X$GTD.city <- sub("costarica", NA, X$GTD.city)
X$GTD.city <- sub("ghana", NA, X$GTD.city)
X$GTD.city <- sub("kazakhstan", NA, X$GTD.city)
X$GTD.city <- sub("netherlands", NA, X$GTD.city)
X$GTD.city <- sub("qatar", NA, X$GTD.city)
X$GTD.city <- sub("togo", NA, X$GTD.city)
X$GTD.city <- sub("yugoslavia", NA, X$GTD.city)
X$GTD.city <- sub("argentina", NA, X$GTD.city)
X$GTD.city <- sub("hungary", NA, X$GTD.city)
X$GTD.city <- sub("malawi", NA, X$GTD.city)
X$GTD.city <- sub("portugal", NA, X$GTD.city)
X$GTD.city <- sub("puertorico", NA, X$GTD.city)
X$GTD.city <- sub("slovakrepublic", NA, X$GTD.city)
X$GTD.city <- sub("solomonislands", NA, X$GTD.city)
X$GTD.city <- sub("sweden", NA, X$GTD.city)
X$GTD.city <- sub("tanzania", NA, X$GTD.city)
X$GTD.city <- sub("trinidadandtobago", NA, X$GTD.city)
X$GTD.city <- sub("bulgaria", NA, X$GTD.city)
X$GTD.city <- sub("canada", NA, X$GTD.city)
X$GTD.city <- sub("comoros", NA, X$GTD.city)
X$GTD.city <- sub("croatia", NA, X$GTD.city)
X$GTD.city <- sub("czechrepublic", NA, X$GTD.city)
X$GTD.city <- sub("equatorialguinea", NA, X$GTD.city)
X$GTD.city <- sub("estonia", NA, X$GTD.city)
X$GTD.city <- sub("japan", NA, X$GTD.city)
X$GTD.city <- sub("latvia", NA, X$GTD.city)
X$GTD.city <- sub("luxembourg", NA, X$GTD.city)
X$GTD.city <- sub("montenegro", NA, X$GTD.city)
X$GTD.city <- sub("antiguaandbarbuda", NA, X$GTD.city)
X$GTD.city <- sub("australia", NA, X$GTD.city)
X$GTD.city <- sub("bahamasthe", NA, X$GTD.city)
X$GTD.city <- sub("belarus", NA, X$GTD.city)
X$GTD.city <- sub("belgium", NA, X$GTD.city)
X$GTD.city <- sub("belize", NA, X$GTD.city)
X$GTD.city <- sub("benin", NA, X$GTD.city)
X$GTD.city <- sub("denmark", NA, X$GTD.city)
X$GTD.city <- sub("fiji", NA, X$GTD.city)
X$GTD.city <- sub("iceland", NA, X$GTD.city)
X$GTD.city <- sub("slovenia", NA, X$GTD.city)
X$GTD.city <- sub("swaziland", NA, X$GTD.city)
X$GTD.city <- sub("vanuatu", NA, X$GTD.city)
X <- subset(X, !is.na(GTD.city))
X$X <- 1
List <- aggregate(X$X, by=list(X$country_txt), FUN=sum)
List <- List[order(-List$x),]



# give a list of cities with distances to cities in the dataset for a specific counrty
X <- PreGTD[which(PreGTD$country_txt == "afghanistan"),]
X <- subset(X, is.na(WCUC.city) & !is.na(GTD.city))
X <- unique(X$GTD.city)
X<- as.character(X)
X <- sub("district", NA, X)
X <- sub(".community$", NA, X)
X <- sub(".commune$", NA, X)
X <- sub(".dist$",  NA, X)
X <- sub(".area$", NA, X)
X <- sub(".border$", NA, X)
X <- sub(".beach$", NA, X)
X <- sub("between.", NA, X)
X <- sub("road", NA, X)
X <- sub("highway", NA, X)
X <- sub("province", NA, X)
X <- sub("municipality", NA, X)
X <- sub("station", NA, X)
X <- sub("forwardoperatingbase", NA, X)
X <- sub("afghanistan", NA, X)
X <- subset(X, !is.na(X))
X <- as.character(X)
X <- data.frame(X, "afghanistan")
X["lookup"] <- paste(X$X, X$X.afghanistan., sep=", ")
afghanistanLOC <- geocode(X$lookup, output = c("latlon", "latlona", "more", "all"), messaging = FALSE, sensor = FALSE, override_limit = TRUE)
afghanistanLOC["CityGTD"] <- X$X
afghanistanLOC <- subset(afghanistanLOC, !is.na(lon))
ZZ <- WC.UC.dist[which(WC.UC.dist$country.etc == "afghanistan"),]
ZZZ <- subset(ZZ, select = c("long", "lat", "name")) 
ZZZ$fake=1
afghanistanLOC$fake=1
Zil <-merge(ZZZ, afghanistanLOC, by=c("fake"))
Zil$lon <- as.numeric(Zil$lon)
Zil$lat.y <- as.numeric(Zil$lat.y)
Zil$long <- as.numeric(Zil$long)
Zil$lat.x <- as.numeric(Zil$lat.x)
Zil["DistKM"] <- gdist(lon.1=Zil$lon, lat.1=Zil$lat.y, lon.2=Zil$long, lat.2=Zil$lat.x, units = "km", a = 6378137, b = 6356752, verbose = FALSE)
Zil.min <- aggregate(DistKM ~ name, Zil, function(x) min(x))
afghanistan.distances <- merge(Zil.min, Zil, by=c("name", "DistKM"))
afghanistan.distances <- afghanistan.distances[order(afghanistan.distances$DistKM),]
write.csv(afghanistan.distances, file="afghanistan.csv")
rm(X,afghanistanLOC, ZZ, ZZZ, Zil, Zil.min)
