UrbanCenters$City <- gsub("\\xc3\xa1","a", perl=TRUE, UrbanCenters$City) 
UrbanCenters$City <- gsub("\\xc3\xa2","a", perl=TRUE, UrbanCenters$City) 
UrbanCenters$City <- gsub("\\xc3\xa3","a", perl=TRUE, UrbanCenters$City) 
UrbanCenters$City <- gsub("\\xc3\xa4","a", perl=TRUE, UrbanCenters$City) 
UrbanCenters$City <- gsub("\\xc3\xa5","a", perl=TRUE, UrbanCenters$City) 
UrbanCenters$City <- gsub("\\xc3\xa0","a", perl=TRUE, UrbanCenters$City) 
UrbanCenters$City <- gsub("\\xc3\xa8","e", perl=TRUE, UrbanCenters$City) 
UrbanCenters$City <- gsub("\\xc3\xa9","e", perl=TRUE, UrbanCenters$City) 
UrbanCenters$City <- gsub("\\xc3\xaa","e", perl=TRUE, UrbanCenters$City) 
UrbanCenters$City <- gsub("\\xc3\xab","e", perl=TRUE, UrbanCenters$City) 
UrbanCenters$City <- gsub("\\xc3\xb1","n", perl=TRUE, UrbanCenters$City) 
UrbanCenters$City <- gsub("\\xc3\xb2","o", perl=TRUE, UrbanCenters$City) 
UrbanCenters$City <- gsub("\\xc3\xb3","o", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\xb4","o", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\xb5","o", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\xb6","o", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\xb9","u", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\xba","u", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\xbb","u", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\xbc","u", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc5\xab","u", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\xac","i", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\xad","i", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\xae","i", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\xaf","i", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc4\xaf","i", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x80","A", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x81","A", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x82","A", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x83","A", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x84","A", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x85","A", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x88","E", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x89","E", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x8a","E", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x8b","E", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x8c","I", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x8d","I", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x8e","I", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x8f","I", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc4\xb0","I", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x91","N", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x92","O", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x93","O", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x94","O", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x95","O", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x98","O", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x99","U", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x9a","U", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x9c","U", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xc3\x9b","U", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\(.*","", UrbanCenters$City)
UrbanCenters$City <- gsub("\\,.*","", UrbanCenters$City)
UrbanCenters$City <- gsub("\\[.+?\\]","", UrbanCenters$City)
UrbanCenters$City <- gsub("\\(.+?\\)","", UrbanCenters$City)
UrbanCenters$City <- gsub("[[:digit:]]", "", UrbanCenters$City)
UrbanCenters$City <- gsub("\\xe2\x80\x91.*","", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xe2\x80\x92.*","", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xe2\x80\x93.*","", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\xe2\x80\x94.*","", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("\\x2d.*","", perl=TRUE, UrbanCenters$City)
UrbanCenters$City <- gsub("Region", "", UrbanCenters$City)
UrbanCenters$City <- gsub("Greater ", "", UrbanCenters$City)

